### PR TITLE
1.18 support (WIP)

### LINKED ISSUE #25: Item ID conflict
## Description
Item FILTER ID conflict
https://github.com/poma123/GlobalWarming/blob/c9988a7a8f41e6edf22522ec80c9f51ea252b4a0/src/main/java/me/poma123/globalwarming/Items.java#L23

https://github.com/Slimefun-Addon-Community/Galactifun/blob/e22759e3d3c7e770f86cb14d6bda944c9f6fb8d2/src/main/java/io/github/addoncommunity/galactifun/base/BaseMats.java#L137 

## Steps to reproduce the Issue
Install [GlobalWarming](https://github.com/poma123/GlobalWarming) and [Galactifun](https://github.com/Slimefun-Addon-Community/Galactifun), start server

## Expected behavior
No conflict error

## Server Log / Error Report
```
[Server thread/ERROR]: Registering SlimefunItem - 'FILTER' (Galactifun vDEV - 37 (git 4a5420dd)) has failed!
io.github.thebusybiscuit.slimefun4.api.exceptions.IdConflictException: Two items have conflicting ids: SlimefunItem - 'FILTER' (Galactifun vDEV - 37 (git 4a5420dd)) and SlimefunItem - 'FILTER' (GlobalWarming vDEV - 10 (git 5d4de1b9))
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.checkForConflicts(SlimefunItem.java:592) ~[Slimefun4.jar:?]
	at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:421) ~[Slimefun4.jar:?]
	at io.github.addoncommunity.galactifun.base.BaseMats.component(BaseMats.java:482) ~[Galactifun.jar:?]
	at io.github.addoncommunity.galactifun.base.BaseMats.component(BaseMats.java:487) ~[Galactifun.jar:?]
	at io.github.addoncommunity.galactifun.base.BaseMats.setup(BaseMats.java:340) ~[Galactifun.jar:?]
	at io.github.addoncommunity.galactifun.Galactifun.enable(Galactifun.java:100) ~[Galactifun.jar:?]
	at io.github.addoncommunity.galactifun.infinitylib.core.AbstractAddon.onEnable(AbstractAddon.java:194) ~[Galactifun.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-399]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-399]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-399]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-399]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-399]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-399]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

## Environment
 - Minecraft Version: Paper 1.17.1
 - Slimefun Version: DEV 986 (git 250fe)
 - Plugin Version: Galactifun vDEV - 37 (git 4a5420dd), GlobalWarming vDEV - 10 (git 5d4de1b9

### LINKED ISSUE #26: Global warming needs to be updated for 1.18 biomes
## Description (REQUIRED)

in the server logs, global warming does not support 1.18 biomes.

## Expected behavior (REQUIRED)

to support 1.18 biomes

## Server Log

https://pastebin.com/ZxihG0Gs

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): paper 81 1.18
 - Minecraft Version: 1.18.1
 - Slimefun Version: 987
 - CS-CoreLib Version: n/a

### PR DESCRIPTION
**Pull request by poma123**
## Description

This Pull Request holds the changes to support 1.18. Currently work in progress.

## Changes
- [x] Minor formatting changes
- [x] Changed FILTER type to be unique
- [x] Use BiomeMaps to handle biome temperatures
- [x] Print missing biomes
- [x] Testinggggggg
## Related Issues

Resolves #25
Resolves #26 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

File: src/main/java/me/poma123/globalwarming/Items.java [hunk 1]
```diff
@@ -20,7 +20,7 @@
     public static final SlimefunItemStack CO2_CANISTER;
     public static final SlimefunItemStack CINNABARITE = new SlimefunItemStack("CINNABARITE", "d67a8a3d7d5aa5db00dff5c82f846ea0aeb7d645f0e467d7e9d9a18e9fa5b012", "&cCinnabarite");
     public static final SlimefunItemStack MERCURY = new SlimefunItemStack("MERCURY", Material.GRAY_DYE, "&7Mercury");
-    public static final SlimefunItemStack FILTER = new SlimefunItemStack("FILTER", Material.GUNPOWDER, "&7Filter");
+    public static final SlimefunItemStack FILTER = new SlimefunItemStack("AIR_COMPRESSOR_FILTER", Material.GUNPOWDER, "&7Filter");
```
Comment (Seggan) [inline src/main/java/me/poma123/globalwarming/Items.java:23]: As stated in the issue, I have resolved this on my end

Comment (poma123) [reply src/main/java/me/poma123/globalwarming/Items.java:23]: I know, but it could happen again and again in the future in my opinion
